dev_ca: &dev_ca
  client_ca_key: "./certs/test/files/ca.key"
  client_ca_cert: "./certs/test/files/ca.crt"
  ca_key_password: nil

cert_options: &cert_options
  client_cert_lifespan: 2
  client_cert_bit_size: 2024
  client_cert_hash: "SHA256"
  allow_limited_certs: false
  allow_unlimited_certs: true
  allow_anonymous_certs: false
  limited_cert_prefix: "LIMITED"
  unlimited_cert_prefix: "UNLIMITED"

development:
  <<: *dev_ca
  <<: *cert_options
  admins: [admin, admin2]
  domain: develop.me

test:
  <<: *dev_ca
  <<: *cert_options
  admins: [admin, admin2]
  domain: test.me

production:
  <<: *cert_options
  admins: []
  domain: deploy.me
